### ISSUE TITLE
[Home page][Landing] قاوم is blue but now clickable 

### ISSUE THREAD

**Issue by AsmaaFailat** [Stand-With-Palestine/CrowdTweet#35]
Steps to reproduce:

1. Open this link https://standwithpalestine.info/home/
2. Click "قاوم"

Actual results:
[Home page][Landing] قاوم is blue but now clickable 

<img width="1904" alt="Screen Shot 2023-10-31 at 3 54 44 PM" src="https://github.com/mtahle/CrowdTweet/assets/36152185/d246f36c-5821-4cbe-b039-934b5ea866bf">

**Comment by Abdulhafeez012** [comment]
@AsmaaFailat This text is not to be clickable, to make attention to the button ( we can change the text after the admin login )
